import type { ConversationItem, ThreadSummary } from "../../../types";
import type { SidebarSnapshot } from "../utils/sidebarSnapshot";
import {
  MAX_ITEM_TEXT,
  normalizeItem,
  prepareThreadItems,
  __getPrepareThreadItemsCallCountForTests,
  __resetPrepareThreadItemsCallCountForTests,
  upsertItem,
} from "../../../utils/threadItems";
import { settlePlanInProgressSteps } from "../utils/threadNormalize";
import {
  isIncrementalDerivationEnabled,
  isReducerNoopGuardEnabled,
} from "../utils/realtimePerfFlags";
import {
  buildLegacyTextDeltaItemId,
  findAssistantMessageIndexByLegacyTextDelta,
  findReasoningIndexById,
  insertLiveReasoningItem,
  isLegacyTextDeltaItemId,
} from "./threadReducerItemLookup";
import {
  isGeminiReasoningThread,
  shouldAcceptReasoningDelta,
} from "./threadReducerReasoningGuards";
import { areEquivalentAssistantMessageTexts } from "../assembly/conversationNormalization";
import {
  addSummaryBoundary,
  findDuplicateReasoningSnapshotIndex,
  isLowRiskStreamingAppendFragmentWithoutBoundary,
  mergeAgentMessageText,
  mergeCompletedAgentText,
  mergeReasoningSnapshotTextForThread,
  mergeReasoningTextForThread,
  mergeStreamingText,
  normalizeReasoningReadableText,
} from "./threadReducerTextMerge";
import {
  findEquivalentCodexAssistantMessageIndex,
  shouldDeduplicateCodexAssistantMessages,
} from "./useThreadsReducerAssistantDedup";
import { isOptimisticUserMessageId } from "../utils/queuedHandoffBubble";
import { isClaudeForkThreadId } from "../utils/claudeForkThread";
import { resolvePendingThreadIdForSession } from "../utils/threadPendingResolution";
import {
  isProcessingGeneratedImageItem,
} from "../utils/generatedImagePlaceholder";
import {
  replaceMatchingProcessingGeneratedImage,
} from "../utils/generatedImagePlaceholderMatching";
import { reduceNormalizedRealtimeEvent } from "./threadReducerNormalizedRealtime";
import {
  insertGeneratedImagesAfterAnchors,
  replaceOptimisticUserAndExtractAnchoredGeneratedImages,
} from "./threadReducerOptimisticUserReconciliation";
import { isSameApprovalRequest } from "./threadReducerApprovalRequests";
import {
  clearAssistantFinalMetadata,
  shouldPreserveAssistantFinalMetadata,
} from "./threadReducerAssistantFinalMetadata";
import { mergeThreadItemsPreservingOptimisticUsers } from "./threadReducerOptimisticItemMerge";
import {
  dropLatestLocalReviewStart,
  ensureUniqueReviewId,
  findMatchingReview,
  isDuplicateReviewById,
} from "./threadReducerReviewItems";
import { shouldFinalizeToolStatus } from "./threadReducerToolStatus";
import {
  extractRenameText,
  isRetainableFinalizedCodexThread,
  looksAutoGeneratedThreadName,
  maybeRenameThreadFromAgent,
  shouldPreferExistingThreadName,
} from "./threadReducerThreadNaming";
import {
  buildCodexCompactionMessage,
  canUseLiveAssistantDeltaFastPath,
  collectThreadScopedCodexCompactionMessages,
  filterThreadScopedCodexCompactionMessages,
  findAssistantMessageIndexById,
  findAssistantMessageIndexByPrefix,
  isAssistantMessageItem,
  isThreadScopedCodexCompactionMessage,
  isThreadTokenUsageEqual,
  isToolConversationItem,
  isUserMessageItem,
  resolveLiveAssistantMessageId,
  resolveLiveReasoningItemId,
  withThreadStatusDefaults,
} from "./threadReducerCoreHelpers";
import type {
  CodexCompactionLifecycleState,
  ThreadAction,
  ThreadActivityStatus,
  ThreadState,
} from "./threadReducerTypes";
import {
  attachReplacedThreadId,
  renameThreadStateIdentity,
} from "./threadReducerThreadIdentity";
export type { ThreadAction, ThreadState } from "./threadReducerTypes";

const REDUCER_NOOP_GUARD_ENABLED = isReducerNoopGuardEnabled();
const INCREMENTAL_DERIVATION_ENABLED = isIncrementalDerivationEnabled();
const PENDING_THREAD_LAST_AGENT_ANCHOR_TTL_MS = 5 * 60 * 1000;
// Continuation evidence arrives once per engine event (heartbeat/delta/item/*)
// via raw dispatch, bypassing the delta batching layers. Consumers only do
// monotonic `>` comparisons on continuationPulse, so per-thread throttling is
// safe and keeps engine progress from forcing app-shell-root re-renders on
// every event.
const CONTINUATION_EVIDENCE_MIN_INTERVAL_MS = 1000;
type ThreadsReducerProfileSnapshot = {
  componentRenderCounts: Record<string, number>;
  prepareThreadItemsCallCount: number;
  reducerDispatchCount: number;
};
type GeneratedImageItem = Extract<ConversationItem, { kind: "generatedImage" }>;
const emptyItems: Record<string, ConversationItem[]> = {};
const threadsReducerProfileState = {
  componentRenderCounts: {} as Record<string, number>,
  reducerDispatchCount: 0,
};

export const __profile = {
  recordComponentRender(componentName: string) {
    const normalizedName = componentName.trim();
    if (!normalizedName) {
      return;
    }
    threadsReducerProfileState.componentRenderCounts[normalizedName] =
      (threadsReducerProfileState.componentRenderCounts[normalizedName] ?? 0) + 1;
  },
  reset() {
    threadsReducerProfileState.componentRenderCounts = {};
    threadsReducerProfileState.reducerDispatchCount = 0;
    __resetPrepareThreadItemsCallCountForTests();
  },
  snapshot(): ThreadsReducerProfileSnapshot {
    return {
      componentRenderCounts: {
        ...threadsReducerProfileState.componentRenderCounts,
      },
      prepareThreadItemsCallCount: __getPrepareThreadItemsCallCountForTests(),
      reducerDispatchCount: threadsReducerProfileState.reducerDispatchCount,
    };
  },
};

type ThreadProviderBindingFields = Pick<
  ThreadSummary,
  | "sourceLabel"
  | "providerProfileId"
  | "providerProfileSource"
  | "providerProfileName"
  | "providerAvailability"
>;

function normalizeProviderBindingValue(value: string | null | undefined) {
  return typeof value === "string" && value.trim().length > 0
    ? value.trim()
    : undefined;
}

function providerBindingFromEnsureThreadAction(
  action: Extract<ThreadAction, { type: "ensureThread" }>,
): Partial<ThreadProviderBindingFields> {
  const sourceLabel = normalizeProviderBindingValue(action.sourceLabel);
  const providerProfileId = normalizeProviderBindingValue(action.providerProfileId);
  const providerProfileSource = normalizeProviderBindingValue(
    action.providerProfileSource,
  );
  const providerProfileName = normalizeProviderBindingValue(action.providerProfileName);
  const providerAvailability = normalizeProviderBindingValue(action.providerAvailability);
  return {
    ...(sourceLabel ? { sourceLabel } : {}),
    ...(providerProfileId ? { providerProfileId } : {}),
    ...(providerProfileSource ? { providerProfileSource } : {}),
    ...(providerProfileName ? { providerProfileName } : {}),
    ...(providerAvailability ? { providerAvailability } : {}),
  };
}

function providerBindingFieldsEqual(
  left: Partial<ThreadProviderBindingFields>,
  right: Partial<ThreadProviderBindingFields>,
) {
  return (
    (left.sourceLabel ?? undefined) === (right.sourceLabel ?? undefined) &&
    (left.providerProfileId ?? undefined) ===
      (right.providerProfileId ?? undefined) &&
    (left.providerProfileSource ?? undefined) ===
      (right.providerProfileSource ?? undefined) &&
    (left.providerProfileName ?? undefined) ===
      (right.providerProfileName ?? undefined) &&
    (left.providerAvailability ?? undefined) ===
      (right.providerAvailability ?? undefined)
  );
}

function shallowRecordEqual(
  left: Record<string, unknown>,
  right: Record<string, unknown>,
) {
  const leftKeys = Object.keys(left);
  const rightKeys = Object.keys(right);
  if (leftKeys.length !== rightKeys.length) {
    return false;
  }
  return leftKeys.every((key) => Object.is(left[key], right[key]));
}

function conversationItemsShallowEqual(
  left: ConversationItem,
  right: ConversationItem,
) {
  return shallowRecordEqual(
    left as unknown as Record<string, unknown>,
    right as unknown as Record<string, unknown>,
  );
}

function threadActivityStatusEqual(
  left: ThreadActivityStatus | undefined,
  right: ThreadActivityStatus,
) {
  if (!left) {
    return false;
  }
  return shallowRecordEqual(
    left as unknown as Record<string, unknown>,
    right as unknown as Record<string, unknown>,
  );
}

function stringArrayEqual(left: string[] | undefined, right: string[] | undefined) {
  if (left === right) {
    return true;
  }
  if (!left || !right || left.length !== right.length) {
    return false;
  }
  return left.every((value, index) => value === right[index]);
}

function autoSessionEqual(
  left: ThreadSummary["autoSession"],
  right: ThreadSummary["autoSession"],
) {
  if (left === right) {
    return true;
  }
  if (!left || !right) {
    return (left ?? null) === (right ?? null);
  }
  return (
    left.sessionPurpose === right.sessionPurpose &&
    left.visibility === right.visibility &&
    left.ownerFeature === right.ownerFeature &&
    (left.autoArchive ?? null) === (right.autoArchive ?? null) &&
    left.createdBy === right.createdBy
  );
}

function threadSummaryEqual(left: ThreadSummary, right: ThreadSummary) {
  return (
    left.id === right.id &&
    left.name === right.name &&
    left.updatedAt === right.updatedAt &&
    (left.archivedAt ?? null) === (right.archivedAt ?? null) &&
    (left.threadKind ?? null) === (right.threadKind ?? null) &&
    (left.sizeBytes ?? null) === (right.sizeBytes ?? null) &&
    (left.engineSource ?? null) === (right.engineSource ?? null) &&
    (left.selectedEngine ?? null) === (right.selectedEngine ?? null) &&
    (left.source ?? null) === (right.source ?? null) &&
    (left.provider ?? null) === (right.provider ?? null) &&
    (left.sourceLabel ?? null) === (right.sourceLabel ?? null) &&
    (left.providerProfileId ?? null) === (right.providerProfileId ?? null) &&
    (left.providerProfileSource ?? null) ===
      (right.providerProfileSource ?? null) &&
    (left.providerProfileName ?? null) === (right.providerProfileName ?? null) &&
    (left.providerAvailability ?? null) ===
      (right.providerAvailability ?? null) &&
    (left.partialSource ?? null) === (right.partialSource ?? null) &&
    (left.isDegraded ?? false) === (right.isDegraded ?? false) &&
    (left.degradedReason ?? null) === (right.degradedReason ?? null) &&
    (left.folderId ?? null) === (right.folderId ?? null) &&
    autoSessionEqual(left.autoSession ?? null, right.autoSession ?? null) &&
    stringArrayEqual(left.nativeThreadIds, right.nativeThreadIds) &&
    (left.parentThreadId ?? null) === (right.parentThreadId ?? null)
  );
}

function threadSummaryListEqual(left: ThreadSummary[], right: ThreadSummary[]) {
  if (left === right) {
    return true;
  }
  if (left.length !== right.length) {
    return false;
  }
  return left.every((thread, index) => {
    const rightThread = right[index];
    return rightThread ? threadSummaryEqual(thread, rightThread) : false;
  });
}

function findEquivalentAssistantSnapshotIndex(
  list: ConversationItem[],
  incomingText: string,
) {
  if (!incomingText.trim()) {
    return -1;
  }
  for (let index = list.length - 1; index >= 0; index -= 1) {
    const item = list[index];
    if (isUserMessageItem(item)) {
      return -1;
    }
    if (!isAssistantMessageItem(item)) {
      continue;
    }
    if (
      areEquivalentAssistantMessageTexts(
        item.text,
        incomingText,
        mergeCompletedAgentText,
      )
    ) {
      return index;
    }
  }
  return -1;
}

function mergeProviderBindingFields<T extends ThreadSummary>(
  incoming: T,
  existing?: ThreadSummary,
): T {
  if (!existing) {
    return incoming;
  }
  return {
    ...incoming,
    sourceLabel: incoming.sourceLabel ?? existing.sourceLabel,
    providerProfileId: incoming.providerProfileId ?? existing.providerProfileId,
    providerProfileSource:
      incoming.providerProfileSource ?? existing.providerProfileSource,
    providerProfileName:
      incoming.providerProfileName ?? existing.providerProfileName,
    providerAvailability:
      incoming.providerAvailability ?? existing.providerAvailability,
  };
}

export const initialState: ThreadState = {
  activeThreadIdByWorkspace: {},
  itemsByThread: emptyItems,
  historyRestoredAtMsByThread: {},
  threadsByWorkspace: {},
  hiddenThreadIdsByWorkspace: {},
  threadParentById: {},
  threadStatusById: {},
  threadListLoadingByWorkspace: {},
  threadListPagingByWorkspace: {},
  threadListCursorByWorkspace: {},
  activeTurnIdByThread: {},
  codexAcceptedTurnByThread: {},
  approvals: [],
  userInputRequests: [],
  tokenUsageByThread: {},
  rateLimitsByWorkspace: {},
  accountByWorkspace: {},
  planByThread: {},
  lastAgentMessageByThread: {},
  agentSegmentByThread: {},
};

export function createInitialThreadState(snapshot?: SidebarSnapshot | null): ThreadState {
  if (!snapshot) {
    return initialState;
  }
  return {
    ...initialState,
    threadsByWorkspace: snapshot.threadsByWorkspace,
  };
}

export function threadReducer(state: ThreadState, action: ThreadAction): ThreadState {
  threadsReducerProfileState.reducerDispatchCount += 1;
  switch (action.type) {
    case "setActiveThreadId": {
      const currentActiveThreadId =
        state.activeThreadIdByWorkspace[action.workspaceId] ?? null;
      const activeThreadUnchanged = currentActiveThreadId === action.threadId;
      const nextActiveThreadIdByWorkspace = activeThreadUnchanged
        ? state.activeThreadIdByWorkspace
        : {
            ...state.activeThreadIdByWorkspace,
            [action.workspaceId]: action.threadId,
          };
      if (!action.threadId) {
        return activeThreadUnchanged
          ? state
          : {
              ...state,
              activeThreadIdByWorkspace: nextActiveThreadIdByWorkspace,
            };
      }
      const currentStatus = state.threadStatusById[action.threadId];
      const nextStatus = {
        ...withThreadStatusDefaults(currentStatus),
        hasUnread: false,
      };
      const statusUnchanged = threadActivityStatusEqual(
        currentStatus,
        nextStatus,
      );
      if (activeThreadUnchanged && statusUnchanged) {
        return state;
      }
      return {
        ...state,
        activeThreadIdByWorkspace: nextActiveThreadIdByWorkspace,
        threadStatusById: statusUnchanged
          ? state.threadStatusById
          : {
              ...state.threadStatusById,
              [action.threadId]: nextStatus,
            },
      };
    }
    case "ensureThread": {
      const hidden =
        state.hiddenThreadIdsByWorkspace[action.workspaceId]?.[action.threadId] ??
        false;
      if (hidden) {
        return state;
      }
      const list = state.threadsByWorkspace[action.workspaceId] ?? [];
      let existingIndex = list.findIndex((thread) => thread.id === action.threadId);
      if (existingIndex < 0 && !action.threadId.includes(":")) {
        const aliasIndexes = list
          .map((thread, index) => ({ thread, index }))
          .filter(({ thread }) => thread.id.endsWith(`:${action.threadId}`))
          .map(({ index }) => index);
        if (aliasIndexes.length === 1) {
          existingIndex = aliasIndexes[0] ?? -1;
        }
      }
      if (existingIndex >= 0) {
        const existing = list[existingIndex];
        if (!existing) {
          return state;
        }
        // BUG FIX: Only update engineSource if action.engine is explicitly provided
        // AND the existing engineSource is not already set.
        // This prevents inferred engines (from inferEngineFromThreadId) from
        // overwriting explicitly set engines.
        if (
          (!action.engine || existing.engineSource) &&
          action.folderId === undefined &&
          action.autoSession === undefined &&
          action.sourceLabel === undefined &&
          action.providerProfileId === undefined &&
          action.providerProfileSource === undefined &&
          action.providerProfileName === undefined &&
          action.providerAvailability === undefined
        ) {
          return state;
        }
        const providerBindingPatch = providerBindingFromEnsureThreadAction(action);
        const updated = {
          ...existing,
          engineSource: action.engine ?? existing.engineSource,
          folderId: action.folderId ?? existing.folderId,
          autoSession: action.autoSession ?? existing.autoSession ?? null,
          ...providerBindingPatch,
        };
        if (
          updated.engineSource === existing.engineSource &&
          updated.folderId === existing.folderId &&
          updated.autoSession === existing.autoSession &&
          providerBindingFieldsEqual(updated, existing)
        ) {
          return state;
        }
        const nextList = [...list];
        nextList[existingIndex] = updated;
        return {
          ...state,
          threadsByWorkspace: {
            ...state.threadsByWorkspace,
            [action.workspaceId]: nextList,
          },
        };
      }

      // CRITICAL FIX: Handle race condition between renameThreadId and subsequent events.
      // If threadId is engine:{sessionId} but not found, check for pending thread to rename.
      const pendingEngine = action.threadId.startsWith("claude:")
        ? "claude"
        : action.threadId.startsWith("gemini:")
          ? "gemini"
        : action.threadId.startsWith("opencode:")
          ? "opencode"
          : null;
      if (pendingEngine) {
        const pendingThreadId = resolvePendingThreadIdForSession({
          workspaceId: action.workspaceId,
          engine: pendingEngine,
          threadsByWorkspace: state.threadsByWorkspace,
          activeThreadIdByWorkspace: state.activeThreadIdByWorkspace,
          threadStatusById: state.threadStatusById,
          activeTurnIdByThread: state.activeTurnIdByThread,
          itemsByThread: state.itemsByThread,
        });
        const pendingIndex = pendingThreadId === null
          ? -1
          : list.findIndex((thread) => thread.id === pendingThreadId);

        if (pendingIndex >= 0) {
          // Found a pending thread - perform inline rename to avoid race condition
          const pendingThread = list[pendingIndex];
          if (!pendingThread) {
            return state;
          }
          const oldThreadId = pendingThread.id;
          const newThreadId = action.threadId;

          // Rename thread inline (similar to renameThreadId action)
          const updatedThread = attachReplacedThreadId(
            {
              ...pendingThread,
              id: newThreadId,
              ...providerBindingFromEnsureThreadAction(action),
            },
            oldThreadId,
          );
          const nextList = [...list];
          nextList[pendingIndex] = updatedThread;

          // Update all related state maps
          const newItemsByThread = { ...state.itemsByThread };
          if (newItemsByThread[oldThreadId]) {
            newItemsByThread[newThreadId] = newItemsByThread[oldThreadId];
            delete newItemsByThread[oldThreadId];
          }

          const newThreadStatusById = { ...state.threadStatusById };
          if (newThreadStatusById[oldThreadId]) {
            newThreadStatusById[newThreadId] = newThreadStatusById[oldThreadId];
            delete newThreadStatusById[oldThreadId];
          }

          const newActiveTurnIdByThread = { ...state.activeTurnIdByThread };
          if (newActiveTurnIdByThread[oldThreadId] !== undefined) {
            newActiveTurnIdByThread[newThreadId] = newActiveTurnIdByThread[oldThreadId];
            delete newActiveTurnIdByThread[oldThreadId];
          }

          const newCodexAcceptedTurnByThread = { ...state.codexAcceptedTurnByThread };
          if (newCodexAcceptedTurnByThread[oldThreadId]) {
            newCodexAcceptedTurnByThread[newThreadId] =
              newCodexAcceptedTurnByThread[oldThreadId];
            delete newCodexAcceptedTurnByThread[oldThreadId];
          }

          const newActiveThreadIdByWorkspace = { ...state.activeThreadIdByWorkspace };
          if (newActiveThreadIdByWorkspace[action.workspaceId] === oldThreadId) {
            newActiveThreadIdByWorkspace[action.workspaceId] = newThreadId;
          }

          const newTokenUsageByThread = { ...state.tokenUsageByThread };
          if (newTokenUsageByThread[oldThreadId]) {
            newTokenUsageByThread[newThreadId] = newTokenUsageByThread[oldThreadId];
            delete newTokenUsageByThread[oldThreadId];
          }

          const newPlanByThread = { ...state.planByThread };
          if (newPlanByThread[oldThreadId] !== undefined) {
            newPlanByThread[newThreadId] = newPlanByThread[oldThreadId];
            delete newPlanByThread[oldThreadId];
          }

          const newLastAgentMessageByThread = { ...state.lastAgentMessageByThread };
          if (newLastAgentMessageByThread[oldThreadId]) {
            newLastAgentMessageByThread[newThreadId] = newLastAgentMessageByThread[oldThreadId];
            delete newLastAgentMessageByThread[oldThreadId];
          }

          const newAgentSegmentByThread = { ...state.agentSegmentByThread };
          if (newAgentSegmentByThread[oldThreadId] !== undefined) {
            newAgentSegmentByThread[newThreadId] = newAgentSegmentByThread[oldThreadId];
            delete newAgentSegmentByThread[oldThreadId];
          }

          const newThreadParentById = { ...state.threadParentById };
          if (newThreadParentById[oldThreadId]) {
            if (!isClaudeForkThreadId(oldThreadId)) {
              newThreadParentById[newThreadId] = newThreadParentById[oldThreadId];
            }
            delete newThreadParentById[oldThreadId];
          }
          for (const [threadId, parentId] of Object.entries(newThreadParentById)) {
            if (parentId === oldThreadId) {
              newThreadParentById[threadId] = newThreadId;
            }
          }

          return {
            ...state,
            threadsByWorkspace: {
              ...state.threadsByWorkspace,
              [action.workspaceId]: nextList,
            },
            itemsByThread: newItemsByThread,
            threadStatusById: newThreadStatusById,
            activeTurnIdByThread: newActiveTurnIdByThread,
            codexAcceptedTurnByThread: newCodexAcceptedTurnByThread,
            activeThreadIdByWorkspace: newActiveThreadIdByWorkspace,
            tokenUsageByThread: newTokenUsageByThread,
            planByThread: newPlanByThread,
            lastAgentMessageByThread: newLastAgentMessageByThread,
            agentSegmentByThread: newAgentSegmentByThread,
            threadParentById: newThreadParentById,
          };
        }
      }

      // No existing thread and no pending thread to rename - create new thread
      const fallbackName = action.threadId.startsWith("claude:")
        ? "Claude Session"
        : `Agent ${list.length + 1}`;
      const thread: ThreadSummary = {
        id: action.threadId,
        name: fallbackName,
        // 新建会话以当前时间戳排序，使其出现在列表顶部而非底部（updatedAt: 0 会被排到最旧）
        updatedAt: Date.now(),
        engineSource: action.engine,
        folderId: action.folderId ?? null,
        autoSession: action.autoSession ?? null,
        ...providerBindingFromEnsureThreadAction(action),
      };
      return {
        ...state,
        threadsByWorkspace: {
          ...state.threadsByWorkspace,
          [action.workspaceId]: [thread, ...list],
        },
        threadStatusById: {
          ...state.threadStatusById,
          [action.threadId]: withThreadStatusDefaults(),
        },
        activeThreadIdByWorkspace: {
          ...state.activeThreadIdByWorkspace,
          [action.workspaceId]:
            state.activeThreadIdByWorkspace[action.workspaceId] ?? action.threadId,
        },
      };
    }
    case "hideThread": {
      const hiddenForWorkspace =
        state.hiddenThreadIdsByWorkspace[action.workspaceId] ?? {};
      if (hiddenForWorkspace[action.threadId]) {
        return state;
      }

      const nextHiddenForWorkspace = {
        ...hiddenForWorkspace,
        [action.threadId]: true as const,
      };

      const list = state.threadsByWorkspace[action.workspaceId] ?? [];
      const filtered = list.filter((thread) => thread.id !== action.threadId);
      const nextActive =
        state.activeThreadIdByWorkspace[action.workspaceId] === action.threadId
          ? filtered[0]?.id ?? null
          : state.activeThreadIdByWorkspace[action.workspaceId] ?? null;

      return {
        ...state,
        hiddenThreadIdsByWorkspace: {
          ...state.hiddenThreadIdsByWorkspace,
          [action.workspaceId]: nextHiddenForWorkspace,
        },
        threadsByWorkspace: {
          ...state.threadsByWorkspace,
          [action.workspaceId]: filtered,
        },
        activeThreadIdByWorkspace: {
          ...state.activeThreadIdByWorkspace,
          [action.workspaceId]: nextActive,
        },
      };
    }
    case "removeThread": {
      const list = state.threadsByWorkspace[action.workspaceId] ?? [];
      const filtered = list.filter((thread) => thread.id !== action.threadId);
      const nextActive =
        state.activeThreadIdByWorkspace[action.workspaceId] === action.threadId
          ? filtered[0]?.id ?? null
          : state.activeThreadIdByWorkspace[action.workspaceId] ?? null;
      const { [action.threadId]: _items, ...restItems } = state.itemsByThread;
      const { [action.threadId]: _historyRestoredAt, ...restHistoryRestoredAt } =
        state.historyRestoredAtMsByThread;
      const { [action.threadId]: _status, ...restStatus } = state.threadStatusById;
      const { [action.threadId]: _turns, ...restTurns } = state.activeTurnIdByThread;
      const { [action.threadId]: _codexAcceptedTurn, ...restCodexAcceptedTurn } =
        state.codexAcceptedTurnByThread;
      const { [action.threadId]: _plans, ...restPlans } = state.planByThread;
      const { [action.threadId]: _parents, ...restParents } = state.threadParentById;
      const { [action.threadId]: _tokenUsage, ...restTokenUsage } = state.tokenUsageByThread;
      const { [action.threadId]: _lastAgent, ...restLastAgent } = state.lastAgentMessageByThread;
      const { [action.threadId]: _segments, ...restSegments } = state.agentSegmentByThread;
      return {
        ...state,
        threadsByWorkspace: {
          ...state.threadsByWorkspace,
          [action.workspaceId]: filtered,
        },
        itemsByThread: restItems,
        historyRestoredAtMsByThread: restHistoryRestoredAt,
        threadStatusById: restStatus,
        activeTurnIdByThread: restTurns,
        codexAcceptedTurnByThread: restCodexAcceptedTurn,
        planByThread: restPlans,
        threadParentById: restParents,
        tokenUsageByThread: restTokenUsage,
        lastAgentMessageByThread: restLastAgent,
        agentSegmentByThread: restSegments,
        activeThreadIdByWorkspace: {
          ...state.activeThreadIdByWorkspace,
          [action.workspaceId]: nextActive,
        },
      };
    }
    case "evictThreadItems": {
      if (!action.threadIds.length) {
        return state;
      }
      const nextItemsByThread = { ...state.itemsByThread };
      let didChange = false;
      action.threadIds.forEach((threadId) => {
        if (!(threadId in nextItemsByThread)) {
          return;
        }
        delete nextItemsByThread[threadId];
        didChange = true;
      });
      if (!didChange) {
        return state;
      }
      return {
        ...state,
        itemsByThread: nextItemsByThread,
      };
    }
    case "setThreadParent": {
      if (!action.parentId || action.parentId === action.threadId) {
        return state;
      }
      if (state.threadParentById[action.threadId] === action.parentId) {
        return state;
      }
      return {
        ...state,
        threadParentById: {
          ...state.threadParentById,
          [action.threadId]: action.parentId,
        },
      };
    }
    case "markProcessing": {
      const previous = state.threadStatusById[action.threadId];
      const wasProcessing = previous?.isProcessing ?? false;
      const startedAt = previous?.processingStartedAt ?? null;
      const lastDurationMs = previous?.lastDurationMs ?? null;
      const heartbeatPulse = previous?.heartbeatPulse ?? 0;
      const continuationPulse = previous?.continuationPulse ?? 0;
      const terminalPulse = previous?.terminalPulse ?? 0;
      const compactionSource = previous?.codexCompactionSource ?? null;
      const compactionLifecycleState =
        previous?.codexCompactionLifecycleState ?? "idle";
      const compactionCompletedAt =
        previous?.codexCompactionCompletedAt ?? null;
      const lastTokenUsageUpdatedAt =
        previous?.lastTokenUsageUpdatedAt ?? null;
      const codexSilentSuspectedAt =
        previous?.codexSilentSuspectedAt ?? null;
      const codexSilentSuspectedSource =
        previous?.codexSilentSuspectedSource ?? null;
      if (action.isProcessing) {
        if (REDUCER_NOOP_GUARD_ENABLED && wasProcessing) {
          return state;
        }
        return {
          ...state,
          threadStatusById: {
            ...state.threadStatusById,
            [action.threadId]: {
              isProcessing: true,
              hasUnread: previous?.hasUnread ?? false,
              isReviewing: previous?.isReviewing ?? false,
              isContextCompacting: previous?.isContextCompacting ?? false,
              processingStartedAt:
                wasProcessing && startedAt ? startedAt : action.timestamp,
              lastDurationMs,
              heartbeatPulse: wasProcessing ? heartbeatPulse : 0,
              continuationPulse,
              terminalPulse,
              codexCompactionSource: compactionSource,
              codexCompactionLifecycleState: compactionLifecycleState,
              codexCompactionCompletedAt: compactionCompletedAt,
              lastTokenUsageUpdatedAt,
              codexSilentSuspectedAt,
              codexSilentSuspectedSource,
            },
          },
        };
      }
      if (
        REDUCER_NOOP_GUARD_ENABLED &&
        (!previous ||
          (!wasProcessing &&
            previous.processingStartedAt == null &&
            (previous.heartbeatPulse ?? 0) === 0))
      ) {
        return state;
      }
      const nextDuration =
        wasProcessing && startedAt
          ? Math.max(0, action.timestamp - startedAt)
          : lastDurationMs ?? null;
      return {
        ...state,
        threadStatusById: {
          ...state.threadStatusById,
          [action.threadId]: {
            isProcessing: false,
            hasUnread: previous?.hasUnread ?? false,
            isReviewing: previous?.isReviewing ?? false,
            isContextCompacting: previous?.isContextCompacting ?? false,
            processingStartedAt: null,
            lastDurationMs: nextDuration,
            heartbeatPulse: 0,
            continuationPulse,
            terminalPulse,
            codexCompactionSource: compactionSource,
            codexCompactionLifecycleState: compactionLifecycleState,
            codexCompactionCompletedAt: compactionCompletedAt,
            lastTokenUsageUpdatedAt,
            codexSilentSuspectedAt: null,
            codexSilentSuspectedSource: null,
          },
        },
      };
    }
    case "markContextCompacting": {
      const previous = state.threadStatusById[action.threadId];
      const currentIsCompacting = previous?.isContextCompacting ?? false;
      const actionTimestamp =
        typeof action.timestamp === "number" && Number.isFinite(action.timestamp)
          ? action.timestamp
          : null;
      const previousSource = previous?.codexCompactionSource ?? null;
      const previousLifecycleState =
        previous?.codexCompactionLifecycleState ?? "idle";
      const nextLifecycleState: CodexCompactionLifecycleState = action.isCompacting
        ? "compacting"
        : action.completionStatus === "completed"
          ? "completed"
          : previousLifecycleState === "completed"
            ? "completed"
          : "idle";
      const nextSource =
        action.source !== undefined
          ? action.source
          : nextLifecycleState === "completed" &&
              previousLifecycleState !== "idle"
            ? previousSource
            : null;
      if (
        currentIsCompacting === action.isCompacting &&
        previousLifecycleState === nextLifecycleState &&
        previousSource === nextSource
      ) {
        return state;
      }
      const startedAt = previous?.processingStartedAt ?? null;
      const nextStartedAt = action.isCompacting
        ? (startedAt ?? actionTimestamp ?? Date.now())
        : (previous?.isProcessing ?? false ? startedAt : null);
      const nextDuration = !action.isCompacting && currentIsCompacting
        ? (startedAt || actionTimestamp)
          ? Math.max(
              0,
              (actionTimestamp ?? Date.now()) - (startedAt ?? actionTimestamp ?? Date.now()),
            )
          : previous?.lastDurationMs ?? null
        : previous?.lastDurationMs ?? null;
      const nextCompletedAt = nextLifecycleState === "completed"
        ? (actionTimestamp ?? Date.now())
        : null;
      return {
        ...state,
        threadStatusById: {
          ...state.threadStatusById,
          [action.threadId]: {
            isProcessing: previous?.isProcessing ?? false,
            hasUnread: previous?.hasUnread ?? false,
            isReviewing: previous?.isReviewing ?? false,
            isContextCompacting: action.isCompacting,
            processingStartedAt: nextStartedAt,
            lastDurationMs: nextDuration,
            heartbeatPulse: previous?.heartbeatPulse ?? 0,
            continuationPulse: previous?.continuationPulse ?? 0,
            terminalPulse: previous?.terminalPulse ?? 0,
            codexCompactionSource: nextSource,
            codexCompactionLifecycleState: nextLifecycleState,
            codexCompactionCompletedAt: nextCompletedAt,
            lastTokenUsageUpdatedAt:
              previous?.lastTokenUsageUpdatedAt ?? null,
            codexSilentSuspectedAt:
              previous?.codexSilentSuspectedAt ?? null,
            codexSilentSuspectedSource:
              previous?.codexSilentSuspectedSource ?? null,
          },
        },
      };
    }
    case "markHeartbeat": {
      const previous = state.threadStatusById[action.threadId];
      if (!previous?.isProcessing) {
        return state;
      }
      if (action.pulse <= 0 || action.pulse <= (previous.heartbeatPulse ?? 0)) {
        return state;
      }
      return {
        ...state,
        threadStatusById: {
          ...state.threadStatusById,
          [action.threadId]: {
            ...previous,
            heartbeatPulse: action.pulse,
          },
        },
      };
    }
    case "markContinuationEvidence": {
      const previous = state.threadStatusById[action.threadId];
      if (!action.force) {
        if (!previous?.isProcessing) {
          return state;
        }
        const lastAt = previous.lastContinuationEvidenceAtMs ?? 0;
        if (action.at - lastAt < CONTINUATION_EVIDENCE_MIN_INTERVAL_MS) {
          return state;
        }
      }
      const nextPulse = (previous?.continuationPulse ?? 0) + 1;
      return {
        ...state,
        threadStatusById: {
          ...state.threadStatusById,
          [action.threadId]: {
            ...withThreadStatusDefaults(previous),
            continuationPulse: nextPulse,
            lastContinuationEvidenceAtMs: action.at,
          },
        },
      };
    }
    case "markTerminalSettlement": {
      const previous = state.threadStatusById[action.threadId];
      const nextPulse = (previous?.terminalPulse ?? 0) + 1;
      return {
        ...state,
        threadStatusById: {
          ...state.threadStatusById,
          [action.threadId]: {
            ...withThreadStatusDefaults(previous),
            terminalPulse: nextPulse,
            codexSilentSuspectedAt: null,
            codexSilentSuspectedSource: null,
          },
        },
      };
    }
    case "markCodexSilentSuspected": {
      const previous = withThreadStatusDefaults(
        state.threadStatusById[action.threadId],
      );
      if (
        previous.codexSilentSuspectedAt === action.timestamp &&
        previous.codexSilentSuspectedSource === action.source
      ) {
        return state;
      }
      return {
        ...state,
        threadStatusById: {
          ...state.threadStatusById,
          [action.threadId]: {
            ...previous,
            codexSilentSuspectedAt: action.timestamp,
            codexSilentSuspectedSource: action.source,
          },
        },
      };
    }
    case "clearCodexSilentSuspected": {
      const previous = state.threadStatusById[action.threadId];
      if (
        !previous ||
        (previous.codexSilentSuspectedAt == null &&
          previous.codexSilentSuspectedSource == null)
      ) {
        return state;
      }
      return {
        ...state,
        threadStatusById: {
          ...state.threadStatusById,
          [action.threadId]: {
            ...withThreadStatusDefaults(previous),
            codexSilentSuspectedAt: null,
            codexSilentSuspectedSource: null,
          },
        },
      };
    }
    case "finalizePendingToolStatuses": {
      const list = state.itemsByThread[action.threadId] ?? [];
      let didChange = false;

      const nextItems = list.map((item) => {
        if (item.kind !== "tool") {
          return item;
        }

        if (shouldFinalizeToolStatus(item.status)) {
          didChange = true;
          return {
            ...item,
            status: action.status,
          };
        }

        return item;
      });

      if (!didChange) {
        return state;
      }

      return {
        ...state,
        itemsByThread: {
          ...state.itemsByThread,
          [action.threadId]: prepareThreadItems(nextItems),
        },
      };
    }
    case "setActiveTurnId":
      return {
        ...state,
        activeTurnIdByThread: {
          ...state.activeTurnIdByThread,
          [action.threadId]: action.turnId,
        },
      };
    case "markCodexAcceptedTurn": {
      const previous = state.codexAcceptedTurnByThread[action.threadId];
      if (
        previous?.fact === "accepted" &&
        action.fact !== "accepted"
      ) {
        return state;
      }
      if (
        previous?.fact === action.fact &&
        previous.source === action.source
      ) {
        return state;
      }
      return {
        ...state,
        codexAcceptedTurnByThread: {
          ...state.codexAcceptedTurnByThread,
          [action.threadId]: {
            fact: action.fact,
            source: action.source,
            updatedAt: action.timestamp,
          },
        },
      };
    }
    case "markReviewing":
      return {
        ...state,
        threadStatusById: {
          ...state.threadStatusById,
          [action.threadId]: {
            ...withThreadStatusDefaults(
              state.threadStatusById[action.threadId],
            ),
            isReviewing: action.isReviewing,
          },
        },
      };
    case "markUnread":
      return {
        ...state,
        threadStatusById: {
          ...state.threadStatusById,
          [action.threadId]: {
            ...withThreadStatusDefaults(
              state.threadStatusById[action.threadId],
            ),
            hasUnread: action.hasUnread,
          },
        },
      };
    case "addAssistantMessage": {
      const list = state.itemsByThread[action.threadId] ?? [];
      const message: ConversationItem = {
        id: `${Date.now()}-assistant`,
        kind: "message",
        role: "assistant",
        text: action.text,
      };
      return {
        ...state,
        itemsByThread: {
          ...state.itemsByThread,
          [action.threadId]: prepareThreadItems([...list, message]),
        },
      };
    }
    case "setThreadName": {
      const list = state.threadsByWorkspace[action.workspaceId] ?? [];
      const next = list.map((thread) =>
        thread.id === action.threadId ? { ...thread, name: action.name } : thread,
      );
      return {
        ...state,
        threadsByWorkspace: {
          ...state.threadsByWorkspace,
          [action.workspaceId]: next,
        },
      };
    }
    case "setThreadEngine": {
      const list = state.threadsByWorkspace[action.workspaceId] ?? [];
      const next = list.map((thread) =>
        thread.id === action.threadId
          ? {
              ...thread,
              engineSource: action.engine,
              ...(thread.threadKind === "shared"
                ? { selectedEngine: action.engine }
                : {}),
            }
          : thread,
      );
      return {
        ...state,
        threadsByWorkspace: {
          ...state.threadsByWorkspace,
          [action.workspaceId]: next,
        },
      };
    }
    case "setThreadTimestamp": {
      const list = state.threadsByWorkspace[action.workspaceId] ?? [];
      if (!list.length) {
        return state;
      }
      let didChange = false;
      const next = list.map((thread) => {
        if (thread.id !== action.threadId) {
          return thread;
        }
        const current = thread.updatedAt ?? 0;
        if (current >= action.timestamp) {
          return thread;
        }
        didChange = true;
        return { ...thread, updatedAt: action.timestamp };
      });
      if (!didChange) {
        return state;
      }
      return {
        ...state,
        threadsByWorkspace: {
          ...state.threadsByWorkspace,
          [action.workspaceId]: next,
        },
      };
    }
    case "appendAgentDelta": {
      const segmentedItemId = resolveLiveAssistantMessageId(
        state,
        action.threadId,
        action.itemId,
      );

      const sourceItems = state.itemsByThread[action.threadId] ?? [];
      let index = findAssistantMessageIndexById(sourceItems, segmentedItemId);
      let shouldCanonicalizeLegacyId = false;
      if (index < 0 && !isLegacyTextDeltaItemId(action.threadId, segmentedItemId)) {
        const legacySegmentedItemId = resolveLiveAssistantMessageId(
          state,
          action.threadId,
          buildLegacyTextDeltaItemId(action.threadId),
        );
        index = findAssistantMessageIndexById(sourceItems, legacySegmentedItemId);
        if (index < 0) {
          index = findAssistantMessageIndexByLegacyTextDelta(sourceItems, action.threadId);
        }
        shouldCanonicalizeLegacyId = index >= 0;
      }
      const shouldDeduplicateCodexAssistant = shouldDeduplicateCodexAssistantMessages({
        threadsByWorkspace: state.threadsByWorkspace,
        workspaceId: action.workspaceId,
        threadId: action.threadId,
      });
      if (index < 0 && shouldDeduplicateCodexAssistant) {
        index = findEquivalentCodexAssistantMessageIndex(sourceItems, action.delta);
      }
      let list: ConversationItem[];
      if (index >= 0) {
        const existing = sourceItems[index];
        if (!existing || !isAssistantMessageItem(existing)) {
          return state;
        }
        const isThreadProcessing = Boolean(state.threadStatusById[action.threadId]?.isProcessing);
        const keepFinalMetadata = shouldPreserveAssistantFinalMetadata(
          existing,
          isThreadProcessing,
        );
        const nextId = shouldCanonicalizeLegacyId ? segmentedItemId : existing.id;
        const nextText = mergeAgentMessageText(existing.text, action.delta);
        if (
          INCREMENTAL_DERIVATION_ENABLED &&
          nextId === existing.id &&
          nextText === existing.text
        ) {
          return state;
        }
        const nextBase = keepFinalMetadata
          ? existing
          : clearAssistantFinalMetadata(existing);
        list = sourceItems.slice();
        list[index] = {
          ...nextBase,
          id: nextId,
          text: nextText,
          isFinal: keepFinalMetadata ? true : false,
        };
        if (
          canUseLiveAssistantDeltaFastPath({
            threadId: action.threadId,
            list,
            index,
            shouldCanonicalizeLegacyId,
            keepFinalMetadata,
          })
        ) {
          // 低风险追加片段跳过每 delta 的整段归一化扫描（shouldNormalizeAssistantText
          // 对全文做多趟重复检测）；归一化推迟到下一个边界 delta 或收尾快照。
          if (
            !isLowRiskStreamingAppendFragmentWithoutBoundary(
              existing.text,
              action.delta,
            )
          ) {
            list[index] = normalizeItem(list[index], {
              preserveMessageTextLength: true,
            });
          }
          const nextThreadsByWorkspace = maybeRenameThreadFromAgent({
            workspaceId: action.workspaceId,
            threadId: action.threadId,
            items: list,
            itemId: segmentedItemId,
            hasCustomName: action.hasCustomName,
            threadsByWorkspace: state.threadsByWorkspace,
          });
          return {
            ...state,
            itemsByThread: {
              ...state.itemsByThread,
              [action.threadId]: list,
            },
            threadsByWorkspace: nextThreadsByWorkspace,
          };
        }
      } else {
        list = [
          ...sourceItems,
          {
            id: segmentedItemId,
            kind: "message",
            role: "assistant",
            text: action.delta,
            isFinal: false,
          },
        ];
      }
      const updatedItems = prepareThreadItems(list, {
        preserveMessageTextIds: new Set([segmentedItemId]),
      });
      const nextThreadsByWorkspace = maybeRenameThreadFromAgent({
        workspaceId: action.workspaceId,
        threadId: action.threadId,
        items: updatedItems,
        itemId: segmentedItemId,
        hasCustomName: action.hasCustomName,
        threadsByWorkspace: state.threadsByWorkspace,
      });
      return {
        ...state,
        itemsByThread: {
          ...state.itemsByThread,
          [action.threadId]: updatedItems,
        },
        threadsByWorkspace: nextThreadsByWorkspace,
      };
    }
    case "completeAgentMessage": {
      // \u00a76.1: \u4ee3\u7406\u7ed9 applyCompleteAgentMessageToState, \u4fdd\u8bc1\u65e7\u8c03\u7528\u8def\u5f84\u8bed\u4e49\u4e0d\u53d8\u3002
      const applied = applyCompleteAgentMessageToState(state, {
        workspaceId: action.workspaceId,
        threadId: action.threadId,
        itemId: action.itemId,
        text: action.text,
        hasCustomName: action.hasCustomName,
        timestamp: action.timestamp ?? Date.now(),
      });
      if (applied.noop) {
        return state;
      }
      return {
        ...state,
        itemsByThread: applied.itemsByThread,
        threadsByWorkspace: applied.threadsByWorkspace,
      };
    }
    case "flushAgentCompletedBatch": {
      // \u00a76: 1 dispatch \u5408\u5e76 completeAgentMessage + setThreadTimestamp +
      // setLastAgentMessage + (\u6761\u4ef6) markUnread\u3002\u4e0e\u539f\u591a dispatch \u5e8f \u7b49\u4ef7\u3002
      const applied = applyCompleteAgentMessageToState(state, {
        workspaceId: action.workspaceId,
        threadId: action.threadId,
        itemId: action.itemId,
        text: action.text,
        hasCustomName: action.hasCustomName,
        timestamp: action.timestamp,
      });

      // 1) setThreadTimestamp
      const tsList = state.threadsByWorkspace[action.workspaceId] ?? [];
      let tsChanged = applied.threadsByWorkspace !== state.threadsByWorkspace;
      let nextThreadsByWorkspace = applied.threadsByWorkspace;
      if (!applied.noop) {
        if (tsList.length) {
          let tsDidChange = false;
          const tsNext = tsList.map((thread) => {
            if (thread.id !== action.threadId) {
              return thread;
            }
            const current = thread.updatedAt ?? 0;
            if (current >= action.timestamp) {
              return thread;
            }
            tsDidChange = true;
            return { ...thread, updatedAt: action.timestamp };
          });
          if (tsDidChange) {
            tsChanged = true;
            nextThreadsByWorkspace = {
              ...nextThreadsByWorkspace,
              [action.workspaceId]: tsNext,
            };
          }
        }
      }

      // 2) setLastAgentMessage
      const existingLast =
        state.lastAgentMessageByThread[action.threadId];
      let lastAgentChanged = false;
      let nextLastAgentMessageByThread = state.lastAgentMessageByThread;
      if (
        !existingLast ||
        existingLast.timestamp < action.timestamp
      ) {
        lastAgentChanged = true;
        nextLastAgentMessageByThread = {
          ...state.lastAgentMessageByThread,
          [action.threadId]: { text: action.text, timestamp: action.timestamp },
        };
      }

      // 3) \u6761\u4ef6 markUnread
      let threadStatusChanged = false;
      let nextThreadStatusById = state.threadStatusById;
      if (!action.isActiveThread) {
        const currentStatus = state.threadStatusById[action.threadId];
        const baseStatus = withThreadStatusDefaults(currentStatus);
        if (!baseStatus.hasUnread) {
          threadStatusChanged = true;
          nextThreadStatusById = {
            ...state.threadStatusById,
            [action.threadId]: { ...baseStatus, hasUnread: true },
          };
        }
      }

      if (
        applied.noop &&
        !tsChanged &&
        !lastAgentChanged &&
        !threadStatusChanged
      ) {
        return state;
      }

      return {
        ...state,
        itemsByThread: applied.noop ? state.itemsByThread : applied.itemsByThread,
        threadsByWorkspace: nextThreadsByWorkspace,
        lastAgentMessageByThread: nextLastAgentMessageByThread,
        threadStatusById: nextThreadStatusById,
      };
    }
    case "upsertItem": {
      let list = state.itemsByThread[action.threadId] ?? [];
      const rawAssistantSnapshotText =
        action.item.kind === "message" && action.item.role === "assistant"
          ? action.item.text
          : "";
      const item = normalizeItem(action.item);
      const isUserMessage = isUserMessageItem(item);
      const isOptimisticUser = isUserMessage && isOptimisticUserMessageId(item.id);
      const hadUserMessage = isUserMessage
        ? list.some(
            (entry) =>
              entry.kind === "message" &&
              entry.role === "user" &&
              !isOptimisticUserMessageId(entry.id),
          )
        : false;
      let generatedImagesToReinsertAfterUser: GeneratedImageItem[] = [];
      let replacedOptimisticUserInPlace = false;
      if (isUserMessage && !isOptimisticUser) {
        const optimisticReplacement =
          replaceOptimisticUserAndExtractAnchoredGeneratedImages(list, item);
        list = optimisticReplacement.items;
        generatedImagesToReinsertAfterUser =
          optimisticReplacement.generatedImagesToReinsert;
        replacedOptimisticUserInPlace =
          optimisticReplacement.replacedOptimisticUserInPlace;
      }
      const renameText = isUserMessage ? extractRenameText(item.text) : "";
      if (
        item.kind === "review" &&
        item.state === "started" &&
        !item.id.startsWith("review-start-")
      ) {
        list = dropLatestLocalReviewStart(list);
      }
      if (item.kind === "review" && isDuplicateReviewById(list, item)) {
        return state;
      }
      if (item.kind === "review") {
        const existing = findMatchingReview(list, item);
        if (existing && existing.id !== item.id) {
          return state;
        }
      }
      let nextItem = ensureUniqueReviewId(list, item);
      let didMergeEquivalentAssistantSnapshot = false;
      if (
        nextItem.kind === "generatedImage" &&
        !isProcessingGeneratedImageItem(nextItem)
      ) {
        const replacedList = replaceMatchingProcessingGeneratedImage(
          list,
          nextItem,
        );
        if (replacedList) {
          return {
            ...state,
            itemsByThread: {
              ...state.itemsByThread,
              [action.threadId]: prepareThreadItems(replacedList),
            },
          };
        }
      }
      if (nextItem.kind === "reasoning") {
        const segmentedReasoningId = resolveLiveReasoningItemId(
          state,
          action.threadId,
          nextItem.id,
        );
        if (segmentedReasoningId !== nextItem.id) {
          nextItem = { ...nextItem, id: segmentedReasoningId };
        }
        const existingReasoning = list.find(
          (entry): entry is Extract<ConversationItem, { kind: "reasoning" }> =>
            entry.id === nextItem.id && entry.kind === "reasoning",
        );
        if (existingReasoning) {
          const existingSummary = normalizeReasoningReadableText(existingReasoning.summary);
          const incomingSummary = normalizeReasoningReadableText(nextItem.summary);
          const existingContent = normalizeReasoningReadableText(existingReasoning.content);
          const incomingContent = normalizeReasoningReadableText(nextItem.content);
          nextItem = {
            ...nextItem,
            summary: mergeReasoningSnapshotTextForThread(
              action.threadId,
              existingSummary,
              incomingSummary,
            ),
            content: mergeReasoningSnapshotTextForThread(
              action.threadId,
              existingContent,
              incomingContent,
            ),
          };
        } else {
          const normalizedIncoming = {
            ...nextItem,
            summary: normalizeReasoningReadableText(nextItem.summary),
            content: normalizeReasoningReadableText(nextItem.content),
          };
          const duplicateIndex = findDuplicateReasoningSnapshotIndex(
            list,
            normalizedIncoming,
          );
          if (
            duplicateIndex >= 0 &&
            list[duplicateIndex]?.kind === "reasoning"
          ) {
            const duplicate = list[duplicateIndex] as Extract<
              ConversationItem,
              { kind: "reasoning" }
            >;
            nextItem = {
              ...normalizedIncoming,
              id: duplicate.id,
              summary: mergeReasoningSnapshotTextForThread(
                action.threadId,
                duplicate.summary,
                normalizedIncoming.summary,
              ),
              content: mergeReasoningSnapshotTextForThread(
                action.threadId,
                duplicate.content,
                normalizedIncoming.content,
              ),
            };
          } else {
            nextItem = normalizedIncoming;
          }
        }
      }
      if (
        nextItem.kind === "message" &&
        nextItem.role === "assistant" &&
        shouldDeduplicateCodexAssistantMessages({
          threadsByWorkspace: state.threadsByWorkspace,
          workspaceId: action.workspaceId,
          threadId: action.threadId,
        }) &&
        findAssistantMessageIndexById(list, nextItem.id) < 0
      ) {
        const incomingAssistantText = rawAssistantSnapshotText || nextItem.text;
        const codexEquivalentAssistantIndex = findEquivalentCodexAssistantMessageIndex(
          list,
          incomingAssistantText,
        );
        const equivalentAssistantIndex =
          codexEquivalentAssistantIndex >= 0
            ? codexEquivalentAssistantIndex
            : findEquivalentAssistantSnapshotIndex(list, incomingAssistantText);
        const equivalentAssistant =
          equivalentAssistantIndex >= 0 ? list[equivalentAssistantIndex] : undefined;
        if (isAssistantMessageItem(equivalentAssistant)) {
          const mergedText = mergeCompletedAgentText(
            equivalentAssistant.text,
            incomingAssistantText,
          );
          list = [
            ...list.slice(0, equivalentAssistantIndex),
            {
              ...equivalentAssistant,
              ...nextItem,
              id: equivalentAssistant.id,
              text: mergedText,
            },
            ...list.slice(equivalentAssistantIndex + 1),
          ];
          nextItem = list[equivalentAssistantIndex] ?? nextItem;
          didMergeEquivalentAssistantSnapshot = true;
        }
      }
      if (
        INCREMENTAL_DERIVATION_ENABLED &&
        !didMergeEquivalentAssistantSnapshot &&
        generatedImagesToReinsertAfterUser.length === 0 &&
        !isUserMessage
      ) {
        const existingIndex = list.findIndex(
          (entry) => entry.id === nextItem.id && entry.kind === nextItem.kind,
        );
        if (existingIndex >= 0) {
          const existingSlot = list[existingIndex];
          if (existingSlot !== undefined) {
            // mirror upsertItem's merge semantics inline so we can compare
            // the merged slot against the existing reference
            const mergedSlot = (() => {
              if (
                existingSlot.kind === "tool" &&
                nextItem.kind === "tool"
              ) {
                // tool items are handled inside prepareThreadItems via
                // mergeToolItemPreservingSnapshot; skip the fast path.
                return null;
              }
              if (
                existingSlot.kind === "generatedImage" &&
                nextItem.kind === "generatedImage"
              ) {
                return {
                  ...existingSlot,
                  ...nextItem,
                  status:
                    nextItem.status === "completed" ||
                    nextItem.status === "degraded"
                      ? nextItem.status
                      : existingSlot.status,
                  promptText: nextItem.promptText || existingSlot.promptText,
                  fallbackText: nextItem.fallbackText || existingSlot.fallbackText,
                  anchorUserMessageId:
                    nextItem.anchorUserMessageId ?? existingSlot.anchorUserMessageId,
                  images:
                    nextItem.images.length > 0
                      ? nextItem.images
                      : existingSlot.images,
                };
              }
              return { ...existingSlot, ...nextItem } as ConversationItem;
            })();
            if (
              mergedSlot !== null &&
              conversationItemsShallowEqual(existingSlot, mergedSlot)
            ) {
              return state;
            }
          }
        }
      }
      let nextList = replacedOptimisticUserInPlace
        ? list
        : upsertItem(list, nextItem);
      if (generatedImagesToReinsertAfterUser.length > 0) {
        nextList = insertGeneratedImagesAfterAnchors(
          nextList,
          generatedImagesToReinsertAfterUser,
        );
      }
      const updatedItems = prepareThreadItems(nextList);
      let nextThreadsByWorkspace = state.threadsByWorkspace;
      if (isUserMessage) {
        const threads = state.threadsByWorkspace[action.workspaceId] ?? [];
        const textValue = renameText;
        const updatedThreads = threads.map((thread) => {
          if (thread.id !== action.threadId) {
            return thread;
          }
          const looksAutoGenerated = looksAutoGeneratedThreadName(thread.name);
          const shouldRename =
            !hadUserMessage &&
            textValue.length > 0 &&
            looksAutoGenerated &&
            !action.hasCustomName;
          const nextName = shouldRename ? textValue : thread.name;
          return { ...thread, name: nextName };
        });
        const bumpedThreads = updatedThreads.length
          ? [
              ...updatedThreads.filter((thread) => thread.id === action.threadId),
              ...updatedThreads.filter((thread) => thread.id !== action.threadId),
            ]
          : updatedThreads;
        nextThreadsByWorkspace = {
          ...state.threadsByWorkspace,
          [action.workspaceId]: bumpedThreads,
        };
      }
      return {
        ...state,
        itemsByThread: {
          ...state.itemsByThread,
          [action.threadId]: updatedItems,
        },
        threadsByWorkspace: nextThreadsByWorkspace,
      };
    }
    case "applyNormalizedRealtimeEvent":
      return reduceNormalizedRealtimeEvent(
        state,
        action,
        maybeRenameThreadFromAgent,
      );
    case "clearProcessingGeneratedImages": {
      const list = state.itemsByThread[action.threadId] ?? [];
      const filtered = list.filter(
        (item) => !isProcessingGeneratedImageItem(item),
      );
      if (filtered.length === list.length) {
        return state;
      }
      return {
        ...state,
        itemsByThread: {
          ...state.itemsByThread,
          [action.threadId]: prepareThreadItems(filtered),
        },
      };
    }
    case "setThreadItems": {
      const localItems = state.itemsByThread[action.threadId] ?? [];
      const mergedItems = mergeThreadItemsPreservingOptimisticUsers(
        localItems,
        action.items,
        {
          isProcessing: Boolean(state.threadStatusById[action.threadId]?.isProcessing),
          codexCompactionLifecycleState:
            state.threadStatusById[action.threadId]?.codexCompactionLifecycleState ??
            "idle",
        },
      );
      const preserveMessageTextIds = new Set<string>();
      for (const item of mergedItems) {
        if (
          item.kind === "message" &&
          item.role === "assistant" &&
          item.text.length > MAX_ITEM_TEXT
        ) {
          preserveMessageTextIds.add(item.id);
        }
      }
      return {
        ...state,
        itemsByThread: {
          ...state.itemsByThread,
          [action.threadId]: prepareThreadItems(mergedItems, {
            preserveMessageTextIds,
          }),
        },
      };
    }
    case "setThreadHistoryRestoredAt": {
      const previousTimestamp =
        state.historyRestoredAtMsByThread[action.threadId] ?? null;
      if (previousTimestamp === action.timestamp) {
        return state;
      }
      return {
        ...state,
        historyRestoredAtMsByThread: {
          ...state.historyRestoredAtMsByThread,
          [action.threadId]: action.timestamp,
        },
      };
    }
    case "markLatestAssistantMessageFinal": {
      const list = state.itemsByThread[action.threadId] ?? [];
      if (list.length === 0) {
        return state;
      }
      let latestAssistantIndex = -1;
      for (let index = list.length - 1; index >= 0; index -= 1) {
        const item = list[index];
        if (isAssistantMessageItem(item)) {
          latestAssistantIndex = index;
          break;
        }
      }
      if (latestAssistantIndex < 0) {
        return state;
      }
      const latestAssistant = list[latestAssistantIndex];
      if (!isAssistantMessageItem(latestAssistant)) {
        return state;
      }
      const completedAt =
        latestAssistant.finalCompletedAt ??
        Date.now();
      const status = state.threadStatusById[action.threadId];
      const statusDuration =
        typeof status?.lastDurationMs === "number"
          ? Math.max(0, status.lastDurationMs)
          : null;
      const derivedDuration =
        statusDuration !== null
          ? statusDuration
          : status?.processingStartedAt
            ? Math.max(0, completedAt - status.processingStartedAt)
            : null;
      const durationMs =
        typeof latestAssistant.finalDurationMs === "number"
          ? Math.max(0, latestAssistant.finalDurationMs)
          : derivedDuration;
      const shouldUpdate =
        latestAssistant.isFinal !== true ||
        latestAssistant.finalCompletedAt !== completedAt ||
        latestAssistant.finalDurationMs !== durationMs;
      if (!shouldUpdate) {
        return state;
      }
      const next = [...list];
      next[latestAssistantIndex] = {
        ...latestAssistant,
        isFinal: true,
        finalCompletedAt: completedAt,
        ...(durationMs !== null ? { finalDurationMs: durationMs } : {}),
      };
      return {
        ...state,
        itemsByThread: {
          ...state.itemsByThread,
          [action.threadId]: next,
        },
      };
    }
    case "setLastAgentMessage":
      if (
        state.lastAgentMessageByThread[action.threadId] &&
        state.lastAgentMessageByThread[action.threadId]!.timestamp >= action.timestamp
      ) {
        return state;
      }
      return {
        ...state,
        lastAgentMessageByThread: {
          ...state.lastAgentMessageByThread,
          [action.threadId]: { text: action.text, timestamp: action.timestamp },
        },
      };
    case "renameThreadId": {
      const { workspaceId, oldThreadId, newThreadId } = action;
      return renameThreadStateIdentity({
        state,
        workspaceId,
        oldThreadId,
        newThreadId,
      });
    }
    case "appendReasoningSummary": {
      if (!shouldAcceptReasoningDelta(state, action.threadId)) {
        return state;
      }
      const shouldInsertBeforeAssistant =
        isGeminiReasoningThread(action.threadId) &&
        !state.threadStatusById[action.threadId]?.isProcessing &&
        (state.activeTurnIdByThread[action.threadId] ?? null) === null;
      const segmentedReasoningId = resolveLiveReasoningItemId(
        state,
        action.threadId,
        action.itemId,
      );
      const list = state.itemsByThread[action.threadId] ?? [];
      const index = findReasoningIndexById(list, segmentedReasoningId);
      const base =
        index >= 0
          ? (list[index] as ConversationItem)
          : {
              id: segmentedReasoningId,
              kind: "reasoning",
              summary: "",
              content: "",
            };
      const nextSummary = mergeReasoningTextForThread(
        action.threadId,
        "summary" in base ? base.summary : "",
        action.delta,
      );
      if (
        INCREMENTAL_DERIVATION_ENABLED &&
        index >= 0 &&
        "summary" in base &&
        nextSummary === base.summary
      ) {
        return state;
      }
      const updated: ConversationItem = {
        ...base,
        summary: nextSummary,
      } as ConversationItem;
      if (INCREMENTAL_DERIVATION_ENABLED && index >= 0) {
        const next = [...list];
        next[index] = normalizeItem(updated);
        return {
          ...state,
          itemsByThread: {
            ...state.itemsByThread,
            [action.threadId]: next,
          },
        };
      }
      const next = insertLiveReasoningItem(
        list,
        index,
        updated,
        shouldInsertBeforeAssistant,
      );
      return {
        ...state,
        itemsByThread: {
          ...state.itemsByThread,
          [action.threadId]: prepareThreadItems(next),
        },
      };
    }
    case "appendReasoningSummaryBoundary": {
      if (!shouldAcceptReasoningDelta(state, action.threadId)) {
        return state;
      }
      const shouldInsertBeforeAssistant =
        isGeminiReasoningThread(action.threadId) &&
        !state.threadStatusById[action.threadId]?.isProcessing &&
        (state.activeTurnIdByThread[action.threadId] ?? null) === null;
      const segmentedReasoningId = resolveLiveReasoningItemId(
        state,
        action.threadId,
        action.itemId,
      );
      const list = state.itemsByThread[action.threadId] ?? [];
      const index = findReasoningIndexById(list, segmentedReasoningId);
      const base =
        index >= 0
          ? (list[index] as ConversationItem)
          : {
              id: segmentedReasoningId,
              kind: "reasoning",
              summary: "",
              content: "",
            };
      const nextSummary = addSummaryBoundary("summary" in base ? base.summary : "");
      if (
        INCREMENTAL_DERIVATION_ENABLED &&
        index >= 0 &&
        "summary" in base &&
        nextSummary === base.summary
      ) {
        return state;
      }
      const updated: ConversationItem = {
        ...base,
        summary: nextSummary,
      } as ConversationItem;
      if (INCREMENTAL_DERIVATION_ENABLED && index >= 0) {
        const next = [...list];
        next[index] = normalizeItem(updated);
        return {
          ...state,
          itemsByThread: {
            ...state.itemsByThread,
            [action.threadId]: next,
          },
        };
      }
      const next = insertLiveReasoningItem(
        list,
        index,
        updated,
        shouldInsertBeforeAssistant,
      );
      return {
        ...state,
        itemsByThread: {
          ...state.itemsByThread,
          [action.threadId]: prepareThreadItems(next),
        },
      };
    }
    case "appendContextCompacted": {
      const list = state.itemsByThread[action.threadId] ?? [];
      const id = `context-compacted-${action.turnId}`;
      if (list.some((entry) => entry.id === id)) {
        return state;
      }
      const compactedMessage: ConversationItem = {
        id,
        kind: "message",
        role: "assistant",
        text: "Context compacted.",
      };
      return {
        ...state,
        itemsByThread: {
          ...state.itemsByThread,
          [action.threadId]: prepareThreadItems([...list, compactedMessage]),
        },
      };
    }
    case "settleCodexCompactionMessage": {
      const list = state.itemsByThread[action.threadId] ?? [];
      const fallbackMessageId = action.fallbackMessageId ?? null;
      if (action.appendIfAlreadyCompleted) {
        if (!fallbackMessageId || list.some((entry) => entry.id === fallbackMessageId)) {
          return state;
        }
        return {
          ...state,
          itemsByThread: {
            ...state.itemsByThread,
            [action.threadId]: prepareThreadItems([
              ...list,
              buildCodexCompactionMessage(action.threadId, action.text, fallbackMessageId),
            ]),
          },
        };
      }
      const { latestMatch, matchCount } = collectThreadScopedCodexCompactionMessages(
        list,
        action.threadId,
      );
      if (latestMatch?.text === action.text && matchCount === 1) {
        return state;
      }
      const next = [
        ...filterThreadScopedCodexCompactionMessages(list, action.threadId),
        buildCodexCompactionMessage(
          action.threadId,
          action.text,
          latestMatch?.id ?? fallbackMessageId ?? undefined,
        ),
      ];
      return {
        ...state,
        itemsByThread: {
          ...state.itemsByThread,
          [action.threadId]: prepareThreadItems(next),
        },
      };
    }
    case "appendCodexCompactionMessage": {
      const list = state.itemsByThread[action.threadId] ?? [];
      const lastItem = list[list.length - 1];
      const { latestMatch, matchCount } = collectThreadScopedCodexCompactionMessages(
        list,
        action.threadId,
      );
      const shouldReuseLatestStartedMessage =
        isThreadScopedCodexCompactionMessage(lastItem, action.threadId) &&
        latestMatch?.text === action.text &&
        !latestMatch.id.includes("-completed-");
      if (shouldReuseLatestStartedMessage && matchCount === 1) {
        return state;
      }
      const next = [
        ...filterThreadScopedCodexCompactionMessages(list, action.threadId),
        shouldReuseLatestStartedMessage
          ? latestMatch
          : buildCodexCompactionMessage(action.threadId, action.text),
      ];
      return {
        ...state,
        itemsByThread: {
          ...state.itemsByThread,
          [action.threadId]: prepareThreadItems(next),
        },
      };
    }
    case "discardLatestCodexCompactionMessage": {
      const list = state.itemsByThread[action.threadId] ?? [];
      let existingIndex = -1;
      for (let index = list.length - 1; index >= 0; index -= 1) {
        if (isThreadScopedCodexCompactionMessage(list[index], action.threadId)) {
          existingIndex = index;
          break;
        }
      }
      if (existingIndex < 0) {
        return state;
      }
      const existingItem = list[existingIndex];
      if (
        !isThreadScopedCodexCompactionMessage(existingItem, action.threadId) ||
        existingItem.text !== action.text
      ) {
        return state;
      }
      const next = list.filter((_, index) => index !== existingIndex);
      return {
        ...state,
        itemsByThread: {
          ...state.itemsByThread,
          [action.threadId]: prepareThreadItems(next),
        },
      };
    }
    case "appendReasoningContent": {
      if (!shouldAcceptReasoningDelta(state, action.threadId)) {
        return state;
      }
      const shouldInsertBeforeAssistant =
        isGeminiReasoningThread(action.threadId) &&
        !state.threadStatusById[action.threadId]?.isProcessing &&
        (state.activeTurnIdByThread[action.threadId] ?? null) === null;
      const segmentedReasoningId = resolveLiveReasoningItemId(
        state,
        action.threadId,
        action.itemId,
      );
      const list = state.itemsByThread[action.threadId] ?? [];
      const index = findReasoningIndexById(list, segmentedReasoningId);
      const base =
        index >= 0
          ? (list[index] as ConversationItem)
          : {
              id: segmentedReasoningId,
              kind: "reasoning",
              summary: "",
              content: "",
            };
      const nextContent = mergeReasoningTextForThread(
        action.threadId,
        "content" in base ? base.content : "",
        action.delta,
      );
      if (
        INCREMENTAL_DERIVATION_ENABLED &&
        index >= 0 &&
        "content" in base &&
        nextContent === base.content
      ) {
        return state;
      }
      const updated: ConversationItem = {
        ...base,
        content: nextContent,
      } as ConversationItem;
      if (INCREMENTAL_DERIVATION_ENABLED && index >= 0) {
        const next = [...list];
        next[index] = normalizeItem(updated);
        return {
          ...state,
          itemsByThread: {
            ...state.itemsByThread,
            [action.threadId]: next,
          },
        };
      }
      const next = insertLiveReasoningItem(
        list,
        index,
        updated,
        shouldInsertBeforeAssistant,
      );
      return {
        ...state,
        itemsByThread: {
          ...state.itemsByThread,
          [action.threadId]: prepareThreadItems(next),
        },
      };
    }
    case "dropReasoningItems": {
      const list = state.itemsByThread[action.threadId] ?? [];
      const filtered = list.filter((item) => item.kind !== "reasoning");
      if (filtered.length === list.length) {
        return state;
      }
      return {
        ...state,
        itemsByThread: {
          ...state.itemsByThread,
          [action.threadId]: prepareThreadItems(filtered),
        },
      };
    }
    case "appendToolOutput": {
      const list = state.itemsByThread[action.threadId] ?? [];
      // 流式中的工具输出项几乎总在尾部，从尾扫描与 findAssistantMessageIndexById 一致。
      let index = -1;
      for (let cursor = list.length - 1; cursor >= 0; cursor -= 1) {
        if (list[cursor]?.id === action.itemId) {
          index = cursor;
          break;
        }
      }
      if (index < 0) {
        const placeholder: ConversationItem = {
          id: action.itemId,
          kind: "tool",
          toolType: "commandExecution",
          title: "Command",
          detail: "",
          status: "running",
          output: action.delta,
        };
        return {
          ...state,
          itemsByThread: {
            ...state.itemsByThread,
            [action.threadId]: prepareThreadItems([...list, placeholder]),
          },
        };
      }
      const existing = list[index];
      if (!isToolConversationItem(existing)) {
        return state;
      }
      const nextOutput = mergeStreamingText(existing.output ?? "", action.delta);
      if (
        INCREMENTAL_DERIVATION_ENABLED &&
        nextOutput === (existing.output ?? "")
      ) {
        return state;
      }
      const updated: ConversationItem = {
        ...existing,
        output: nextOutput,
      } as ConversationItem;
      const next = [...list];
      next[index] = updated;
      if (INCREMENTAL_DERIVATION_ENABLED) {
        return {
          ...state,
          itemsByThread: {
            ...state.itemsByThread,
            [action.threadId]: next,
          },
        };
      }
      return {
        ...state,
        itemsByThread: {
          ...state.itemsByThread,
          [action.threadId]: prepareThreadItems(next),
        },
      };
    }
    case "addApproval": {
      const exists = state.approvals.some(
        (item) => isSameApprovalRequest(item, action.approval),
      );
      if (exists) {
        return state;
      }
      return { ...state, approvals: [...state.approvals, action.approval] };
    }
    case "removeApproval":
      return {
        ...state,
        approvals: state.approvals.filter(
          (item) =>
            action.approval
              ? !isSameApprovalRequest(item, action.approval)
              : item.request_id !== action.requestId ||
                item.workspace_id !== action.workspaceId,
        ),
      };
    case "addUserInputRequest": {
      const exists = state.userInputRequests.some(
        (item) =>
          item.request_id === action.request.request_id &&
          item.workspace_id === action.request.workspace_id,
      );
      if (exists) {
        return state;
      }
      return {
        ...state,
        userInputRequests: [...state.userInputRequests, action.request],
      };
    }
    case "removeUserInputRequest":
      return {
        ...state,
        userInputRequests: state.userInputRequests.filter(
          (item) =>
            item.request_id !== action.requestId ||
            item.workspace_id !== action.workspaceId,
        ),
      };
    case "clearUserInputRequestsForThread":
      return {
        ...state,
        userInputRequests: state.userInputRequests.filter(
          (item) =>
            item.workspace_id !== action.workspaceId ||
            item.params.thread_id !== action.threadId,
        ),
      };
    case "setThreads": {
      const hidden = state.hiddenThreadIdsByWorkspace[action.workspaceId] ?? {};
      const isHiddenAutomaticThread = (thread: ThreadSummary) =>
        thread.autoSession?.visibility === "hidden";
      const existingThreads = state.threadsByWorkspace[action.workspaceId] ?? [];
      const now = Date.now();
      const shouldPreserveDegradedCodexFinalizedThreads = action.threads.some(
        (thread) => thread.isDegraded,
      );
      // BUG FIX: Preserve engineSource and other info from existing threads when merging
      // This prevents loss of explicitly set engine types (e.g., Claude) when refreshing thread list
      const existingThreadById = new Map(
        existingThreads.map((thread) => [thread.id, thread]),
      );
      const newThreadIds = new Set(action.threads.map((thread) => thread.id));
      const hasPendingThreadAnchor = (threadId: string) => {
        const hasActiveTurn = (state.activeTurnIdByThread[threadId] ?? null) !== null;
        if (hasActiveTurn) {
          return true;
        }
        const itemCount = state.itemsByThread[threadId]?.length ?? 0;
        const isProcessing = Boolean(state.threadStatusById[threadId]?.isProcessing);
        if (isProcessing && itemCount > 0) {
          return true;
        }
        const lastAgentMessageTimestamp =
          state.lastAgentMessageByThread[threadId]?.timestamp ?? 0;
        const hasRecentAgentMessage =
          lastAgentMessageTimestamp > 0 &&
          now - lastAgentMessageTimestamp <= PENDING_THREAD_LAST_AGENT_ANCHOR_TTL_MS;
        if (hasRecentAgentMessage) {
          return true;
        }
        return state.userInputRequests.some(
          (request) =>
            request.workspace_id === action.workspaceId
            && request.params.thread_id === threadId,
        );
      };

      // Merge incoming threads with preserved existing info
      const visibleThreads = action.threads
        .filter((thread) => !hidden[thread.id] && !isHiddenAutomaticThread(thread))
        .map((thread) => {
          const existing = existingThreadById.get(thread.id);
          if (existing) {
            // Preserve engineSource if new thread doesn't have one
            const engineSource = thread.engineSource || existing.engineSource;
            const threadKind = thread.threadKind || existing.threadKind;
            const selectedEngine = thread.selectedEngine || existing.selectedEngine;
            const nativeThreadIds = thread.nativeThreadIds || existing.nativeThreadIds;
            const autoSession = thread.autoSession ?? existing.autoSession ?? null;
            const name = shouldPreferExistingThreadName(existing.name, thread.name)
              ? existing.name
              : thread.name;
            return mergeProviderBindingFields(
              {
                ...thread,
                name,
                engineSource,
                threadKind,
                selectedEngine,
                nativeThreadIds,
                autoSession,
              },
              existing,
            );
          }
          return thread;
        });

      // BUG FIX: Also preserve threads that are currently active but not in the new list
      // (e.g., newly created Claude threads that haven't been synced to the backend yet)
      const activeThreadId = state.activeThreadIdByWorkspace[action.workspaceId];
      if (activeThreadId) {
        const activeThread = existingThreadById.get(activeThreadId);
        if (
          activeThread &&
          !newThreadIds.has(activeThreadId) &&
          !hidden[activeThreadId] &&
          !isHiddenAutomaticThread(activeThread)
        ) {
          // Prepend the active thread to preserve it
          visibleThreads.unshift(activeThread);
        }
      }

      // Preserve provisional runtime threads until native history can represent them.
      // Claude Fork bootstraps have no native row before their first send, while other
      // pending threads still require a realtime or folder anchor.
      const preservedThreadIds = new Set(visibleThreads.map((thread) => thread.id));
      const provisionalThreadsToPreserve = existingThreads.filter((thread) => {
        const threadId = thread.id;
        if (!threadId.includes("-pending-") && !isClaudeForkThreadId(threadId)) {
          return false;
        }
        if (threadId === activeThreadId) {
          return false;
        }
        if (
          hidden[threadId] ||
          isHiddenAutomaticThread(thread) ||
          newThreadIds.has(threadId) ||
          preservedThreadIds.has(threadId)
        ) {
          return false;
        }
        if (typeof thread.folderId === "string" && thread.folderId.trim().length > 0) {
          return true;
        }
        return isClaudeForkThreadId(threadId) || hasPendingThreadAnchor(threadId);
      });
      provisionalThreadsToPreserve.forEach((thread) => preservedThreadIds.add(thread.id));
      const finalizedCodexToPreserve = shouldPreserveDegradedCodexFinalizedThreads
        ? existingThreads.filter((thread) => {
          const threadId = thread.id;
          if (
            !isRetainableFinalizedCodexThread(thread)
            || threadId === activeThreadId
            || hidden[threadId]
            || isHiddenAutomaticThread(thread)
            || newThreadIds.has(threadId)
            || preservedThreadIds.has(threadId)
          ) {
            return false;
          }
          return true;
        })
        : [];
      finalizedCodexToPreserve.forEach((thread) => preservedThreadIds.add(thread.id));
      const locallyAcceptedCodexToPreserve = existingThreads.filter((thread) => {
        const threadId = thread.id;
        if (
          (thread.engineSource ?? "codex") !== "codex" ||
          !state.codexAcceptedTurnByThread[threadId] ||
          threadId === activeThreadId ||
          hidden[threadId] ||
          isHiddenAutomaticThread(thread) ||
          newThreadIds.has(threadId) ||
          preservedThreadIds.has(threadId)
        ) {
          return false;
        }
        return true;
      });
      locallyAcceptedCodexToPreserve.forEach((thread) => {
        preservedThreadIds.add(thread.id);
      });
      const mergedVisibleThreads =
        provisionalThreadsToPreserve.length > 0 ||
        finalizedCodexToPreserve.length > 0 ||
        locallyAcceptedCodexToPreserve.length > 0
          ? activeThreadId && visibleThreads[0]?.id === activeThreadId
            ? [
              visibleThreads[0],
              ...finalizedCodexToPreserve,
              ...locallyAcceptedCodexToPreserve,
              ...provisionalThreadsToPreserve,
              ...visibleThreads.slice(1),
            ]
            : [
              ...finalizedCodexToPreserve,
              ...locallyAcceptedCodexToPreserve,
              ...provisionalThreadsToPreserve,
              ...visibleThreads,
            ]
          : visibleThreads;
      if (threadSummaryListEqual(existingThreads, mergedVisibleThreads)) {
        return state;
      }
      return {
        ...state,
        threadsByWorkspace: {
          ...state.threadsByWorkspace,
          [action.workspaceId]: mergedVisibleThreads,
        },
      };
    }
    case "setThreadListLoading":
      if (
        (state.threadListLoadingByWorkspace[action.workspaceId] ?? false) ===
        action.isLoading
      ) {
        return state;
      }
      return {
        ...state,
        threadListLoadingByWorkspace: {
          ...state.threadListLoadingByWorkspace,
          [action.workspaceId]: action.isLoading,
        },
      };
    case "setThreadListPaging":
      if (
        (state.threadListPagingByWorkspace[action.workspaceId] ?? false) ===
        action.isLoading
      ) {
        return state;
      }
      return {
        ...state,
        threadListPagingByWorkspace: {
          ...state.threadListPagingByWorkspace,
          [action.workspaceId]: action.isLoading,
        },
      };
    case "setThreadListCursor":
      if (
        (state.threadListCursorByWorkspace[action.workspaceId] ?? null) ===
        action.cursor
      ) {
        return state;
      }
      return {
        ...state,
        threadListCursorByWorkspace: {
          ...state.threadListCursorByWorkspace,
          [action.workspaceId]: action.cursor,
        },
      };
    case "setThreadTokenUsage": {
      const existingStatus = withThreadStatusDefaults(
        state.threadStatusById[action.threadId],
      );
      const previousTokenUsage = state.tokenUsageByThread[action.threadId] ?? null;
      const usageSnapshotChanged = !isThreadTokenUsageEqual(
        previousTokenUsage,
        action.tokenUsage,
      );
      const shouldClearCompletedCompaction =
        existingStatus.codexCompactionLifecycleState === "completed" &&
        usageSnapshotChanged;
      if (!usageSnapshotChanged && !shouldClearCompletedCompaction) {
        return state;
      }
      const tokenUsageUpdatedAt = usageSnapshotChanged
        ? Date.now()
        : existingStatus.lastTokenUsageUpdatedAt;
      return {
        ...state,
        tokenUsageByThread: {
          ...state.tokenUsageByThread,
          [action.threadId]: action.tokenUsage,
        },
        threadStatusById: {
          ...state.threadStatusById,
          [action.threadId]: {
            ...existingStatus,
            codexCompactionLifecycleState: shouldClearCompletedCompaction
              ? "idle"
              : existingStatus.codexCompactionLifecycleState,
            codexCompactionSource: shouldClearCompletedCompaction
              ? null
              : existingStatus.codexCompactionSource,
            codexCompactionCompletedAt: shouldClearCompletedCompaction
              ? null
              : existingStatus.codexCompactionCompletedAt,
            lastTokenUsageUpdatedAt: tokenUsageUpdatedAt,
          },
        },
      };
    }
    case "setRateLimits":
      return {
        ...state,
        rateLimitsByWorkspace: {
          ...state.rateLimitsByWorkspace,
          [action.workspaceId]: action.rateLimits,
        },
      };
    case "setAccountInfo":
      return {
        ...state,
        accountByWorkspace: {
          ...state.accountByWorkspace,
          [action.workspaceId]: action.account,
        },
      };
    case "setThreadPlan":
      return {
        ...state,
        planByThread: {
          ...state.planByThread,
          [action.threadId]: action.plan,
        },
      };
    case "settleThreadPlanInProgress": {
      const current = state.planByThread[action.threadId] ?? null;
      const next = settlePlanInProgressSteps(current, action.targetStatus);
      if (next === current) {
        return state;
      }
      return {
        ...state,
        planByThread: {
          ...state.planByThread,
          [action.threadId]: next,
        },
      };
    }
    case "clearThreadPlan":
      return {
        ...state,
        planByThread: {
          ...state.planByThread,
          [action.threadId]: null,
        },
      };
    case "incrementAgentSegment": {
      // 当 tool item 开始时调用，增加分段计数，确保后续文本创建新的 message
      const current = state.agentSegmentByThread[action.threadId] ?? 0;
      return {
        ...state,
        agentSegmentByThread: {
          ...state.agentSegmentByThread,
          [action.threadId]: current + 1,
        },
      };
    }
    case "resetAgentSegment":
      // 当 turn 完成时调用，重置分段计数
      return {
        ...state,
        agentSegmentByThread: {
          ...state.agentSegmentByThread,
          [action.threadId]: 0,
        },
      };
    default:
      return state;
  }
}


/**
 * §6.1: 抽出 `completeAgentMessage` 主体的 state 推导，让 `flushAgentCompletedBatch`
 * 在 1 dispatch 内复用同一段逻辑。返回 `{ itemsByThread, threadsByWorkspace, noop }`：
 *   - `noop=true` 时调用方应保持原 `state` 不变（与原 case "completeAgentMessage" 早返回一致）
 *   - `noop=false` 时调用方应把这两个字段写回新 state
 *
 * 与原 case 行为完全等价（已通过 §10.3 既有测试套件兜底）。
 */
function applyCompleteAgentMessageToState(
  state: ThreadState,
  params: {
    workspaceId: string;
    threadId: string;
    itemId: string;
    text: string;
    hasCustomName: boolean;
    timestamp: number;
  },
): { itemsByThread: ThreadState["itemsByThread"]; threadsByWorkspace: ThreadState["threadsByWorkspace"]; noop: boolean } {
  const segmentedItemId = resolveLiveAssistantMessageId(
    state,
    params.threadId,
    params.itemId,
  );
  const list = [...(state.itemsByThread[params.threadId] ?? [])];
  let index = findAssistantMessageIndexById(list, segmentedItemId);
  if (index < 0) {
    index = findAssistantMessageIndexById(list, params.itemId);
  }
  if (index < 0) {
    index = findAssistantMessageIndexByPrefix(list, params.itemId);
  }
  let shouldCanonicalizeLegacyId = false;
  if (index < 0 && !isLegacyTextDeltaItemId(params.threadId, segmentedItemId)) {
    const legacySegmentedItemId = resolveLiveAssistantMessageId(
      state,
      params.threadId,
      buildLegacyTextDeltaItemId(params.threadId),
    );
    index = findAssistantMessageIndexById(list, legacySegmentedItemId);
    if (index < 0) {
      index = findAssistantMessageIndexByLegacyTextDelta(list, params.threadId);
    }
    shouldCanonicalizeLegacyId = index >= 0;
  }
  const shouldDeduplicateCodexAssistant = shouldDeduplicateCodexAssistantMessages({
    threadsByWorkspace: state.threadsByWorkspace,
    workspaceId: params.workspaceId,
    threadId: params.threadId,
  });
  if (index < 0 && shouldDeduplicateCodexAssistant) {
    index = findEquivalentCodexAssistantMessageIndex(list, params.text);
  }
  const targetItemId =
    index >= 0
      ? shouldCanonicalizeLegacyId
        ? segmentedItemId
        : (list[index]?.id ?? segmentedItemId)
      : segmentedItemId;
  const completedAt = params.timestamp ?? Date.now();
  const status = state.threadStatusById[params.threadId];
  const statusDuration =
    typeof status?.lastDurationMs === "number"
      ? Math.max(0, status.lastDurationMs)
      : null;
  const derivedDuration =
    statusDuration !== null
      ? statusDuration
      : status?.processingStartedAt
        ? Math.max(0, completedAt - status.processingStartedAt)
        : null;
  const existingItem = index >= 0 ? list[index] : undefined;
  let computedCompletedItem: ConversationItem | null = null;
  if (isAssistantMessageItem(existingItem)) {
    const isThreadProcessing = Boolean(state.threadStatusById[params.threadId]?.isProcessing);
    const keepFinalMetadata = shouldPreserveAssistantFinalMetadata(
      existingItem,
      isThreadProcessing,
    );
    const nextBase = keepFinalMetadata
      ? existingItem
      : clearAssistantFinalMetadata(existingItem);
    computedCompletedItem = {
      ...nextBase,
      id: targetItemId,
      text: mergeCompletedAgentText(
        existingItem.text,
        params.text,
        true,
      ),
      isFinal: true,
      finalCompletedAt: nextBase.finalCompletedAt ?? completedAt,
      ...(typeof nextBase.finalDurationMs === "number"
        ? { finalDurationMs: nextBase.finalDurationMs }
        : derivedDuration !== null
          ? { finalDurationMs: derivedDuration }
          : {}),
    };
  } else {
    computedCompletedItem = {
      id: targetItemId,
      kind: "message",
      role: "assistant",
      text: params.text,
      isFinal: true,
      finalCompletedAt: completedAt,
      ...(derivedDuration !== null ? { finalDurationMs: derivedDuration } : {}),
    };
  }
  if (
    INCREMENTAL_DERIVATION_ENABLED &&
    isAssistantMessageItem(existingItem) &&
    existingItem !== undefined &&
    targetItemId === existingItem.id &&
    existingItem.isFinal === true &&
    derivedDuration === null
  ) {
    const mergedCompletedText = mergeCompletedAgentText(
      existingItem.text,
      params.text,
      true,
    );
    if (mergedCompletedText === existingItem.text) {
      return {
        itemsByThread: state.itemsByThread,
        threadsByWorkspace: state.threadsByWorkspace,
        noop: true,
      };
    }
  }
  if (computedCompletedItem !== null) {
    if (isAssistantMessageItem(existingItem) && index >= 0) {
      list[index] = computedCompletedItem;
    } else {
      list.push(computedCompletedItem);
    }
  }
  const updatedItems = prepareThreadItems(list, {
    preserveMessageTextIds: new Set([targetItemId]),
  });
  const nextThreadsByWorkspace = maybeRenameThreadFromAgent({
    workspaceId: params.workspaceId,
    threadId: params.threadId,
    items: updatedItems,
    itemId: targetItemId,
    hasCustomName: params.hasCustomName,
    threadsByWorkspace: state.threadsByWorkspace,
  });
  return {
    itemsByThread: {
      ...state.itemsByThread,
      [params.threadId]: updatedItems,
    },
    threadsByWorkspace: nextThreadsByWorkspace,
    noop: false,
  };
}
